dev:
  propel:
    param:
      classname:  DebugPDO

test:
  propel:
    param:
      classname:  DebugPDO

all:
  propel:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=prueba;host=localhost
      username:   root_prueba
      password:   123456
      encoding:   utf8
      persistent: true
      pooling:    true
